### ISSUE TITLE
Registry for img.badgesize.io has expired!

### ISSUE THREAD

**Issue by MSNev** [ngryman/badge-size#113]
WHOIS search results
Domain Name: badgesize.io
Registry Domain ID: 5cab44e96c4d426babc7588c50d04f88-DONUTS
Registrar WHOIS Server: whois.1api.net
Registrar URL: http://www.1api.net
Updated Date: 2024-03-24T19:09:19Z
Creation Date: 2016-02-09T18:38:33Z
**Registry Expiry Date: 2024-02-09T18:38:33Z**
Registrar: 1API GmbH

**Comment by MSNev** [comment]
Is / Are they any plans to reactivate the `badgesize.io` domain or is this project and the implementation (service) considered to be defunction / deprecated etc?

**Comment by franciscop** [comment]
Twitter seems unused, maybe he quit the internet:

https://twitter.com/ngryman

**Comment by nev21** [comment]
It appears that someone has grabbed this domain and is currently actively promoting spam / malware on the root domain 😞 

I was attempting / watching the domain to try and avoid this situation... 😒

**Comment by nev21** [comment]
FYI - I now have now obtained control of the badgesize.io domain and I'm in the process of organizing some support again. Based on some of nicks comments around costs I'm evaluating the path forward. But I do intend to provide some level of free support as we had prior to the domain expiring.

**Comment by nev21** [comment]
I've now brought an initial version online to serve badges, will be evaluating over the next few days the volume of traffic and adjustments will likelye be made in the coming weeks.

**Comment by nev21** [comment]
PR #114 to provide link to new home

**Comment by ngryman** [comment]
Hey everyone, sorry for the **very late** answer...

I didn't quit the Internet but unfortunately I didn't have the time to maintain this project anymore. I'm sorry if it caused any sort of trouble.

@nev21 Glad you took the initiative to fork and host the project. I merged your PR.
