### ISSUE TITLE
Always shows gzipped size

### ISSUE THREAD

**Issue by bfred-it** [ngryman/badge-size#2]
image | url
--- | ---
![module size](https://badge-size.herokuapp.com/ngryman/badge-size/master/index.js.svg) |  https://badge-size.herokuapp.com/ngryman/badge-size/master/index.js.svg
![module size](https://badge-size.herokuapp.com/ngryman/badge-size/master/index.js.svg?compression=gzip) | https://badge-size.herokuapp.com/ngryman/badge-size/master/index.js.svg?compression=gzip

**Comment by ngryman** [comment]
Thanks for pointing it out.
I was fetching gzipped content from **Github** instead of plain text.
This has been fixed by enforcing a plain text request with `accept-encoding: identity`.

**Comment by bfred-it** [comment]
Sweet! Thanks :)
