### ISSUE TITLE
Still caching

### ISSUE THREAD

**Issue by nathancahill** [ngryman/badge-size#36]
After the 49eca18 revert, #4 is an issue again. Github's camo or Github's markdown processing is caching image responses. See the badge here: https://github.com/nathancahill/Split.js/ (displays 1.89 kb) and the correct file size: https://badge-size.herokuapp.com/nathancahill/Split.js/master/split.min.js.svg?compression=gzip&label=size (displays 2.05 kb). Was there a reason to return the response instead of proxying?

**Comment by ngryman** [comment]
Hey @nathancahill,

Yes there was a reason, but I must admit that I don't remember exactly 😢 (I should have detailed this in the commit...).
But from what I remember, `raw.githubusercontent.com` has a short cache too (like 5min) and it gives the impression that the badge is cached by `camo`, but it's not.

Did you test like 10 minutes later? Your links both give me `1.98kb`. You can also use the `img.badgesize.io` domain instead (nicer 😄)

**Comment by ngryman** [comment]
Some clues in the code: https://github.com/ngryman/badge-size/blob/master/index.js#L149.
I did commented my code yay :man_dancing:

**Comment by nathancahill** [comment]
Ah, cool. Looks good, thanks!
