### ISSUE TITLE
Feature Request: Accept the bundle size as a parameter

### ISSUE THREAD

**Issue by jasonkarns** [ngryman/badge-size#37]
I would love to use this badge service for modules on our internal Github Enterprise. This would obviously mean that the badge service can't pull the file to check the size automatically. However, if the file-size were an optional parameter, then we could still use the service.

We have an npm-script that checks file size of the dist files after a build. We could write this info directly into the README itself as part of the badge URL.

**Comment by ngryman** [comment]
Hey, you better use a service like `shields.io` that let's you create custom badges.
You could do something like `https://img.shields.io/badge/size-1.0%20KB-brightgreen.svg` for exemple>

Ref: http://shields.io/#your-badge
