### ISSUE TITLE
Parse Style Parameters

### ISSUE THREAD

**Issue by webcaetano** [ngryman/badge-size#5]
Hello, awesome repo. 
You guys deserve more stars.

Could please parse the `style` parameter foward, instead of only `-brightgreen`  ?

https://github.com/ngryman/badge-size/blob/master/index.js#L112

**Comment by ngryman** [comment]
Hey, thanks buddy.

Yes sure, I can add additional parameters. To stay compliant with **shileds.io**, I can add:
- `color`: which will fit your needs.
- `style`: which will change the overall style of the badge: http://shields.io/#styles.

I'll ping you when it's done.

**Comment by webcaetano** [comment]
@ngryman thanks.
Awesome.
Let's spread this badge :+1:
