### ISSUE TITLE
Update site to use https

### ISSUE THREAD

**Issue by paulmolluzzo** [ngryman/badge-size#62]
When using `badge-size` on a site using `https`, the browser displays mixed content warning. Would you consider using SSL on the site to avoid this error?

It's pretty easy to do with [now](https://now.sh). I just deployed it myself in about 2 mins: https://badge-size-mpcfddqqgp.now.sh 😄 

![](https://user-images.githubusercontent.com/3070389/29025421-e3bca552-7b76-11e7-9906-e5e06cea6ca7.png)

See: https://github.com/kentcdodds/glamorous-website/issues/265 for an example

**Comment by paulmolluzzo** [comment]
https://badge-size-mpcfddqqgp.now.sh/https://www.npmjs.com/package/badge-size

**Comment by ngryman** [comment]
@paulmolluzzo Good idea, thanks!

From their pricing page:
> For certain open source projects we sponsor support for custom domains. Please contact us to find out if yours applies.

I've sent them an email to see if I could use `badgesize.io`. If so, I don't see any reason not to switch to `now`. I'll keep you posted.

**Comment by botic** [comment]
Any response from them? Or should someone send them a trigger tweet? ;)

**Comment by ngryman** [comment]
@botic No response for now. I don't know if they'll react on Twitter, if you know some bigger guy than me, go!

**Comment by styfle** [comment]
@ngryman Yes, you can use custom domains with zeit now. See [aliases & domains](https://zeit.co/docs/features/aliases) in the docs.

**Comment by ngryman** [comment]
Hey @styfle,

Oh nice, if it's available out of the box, I'm going to switch now.
Thanks for the help proposal! As I would like this project to be as simple as possible, do you have an idea of potential improvements/features?

PS: Package Phobia is cool 👍

**Comment by styfle** [comment]
Oh yeah, I think there is [a process](https://zeit.co/account/plan) to get Open Source hosted with a custom domain:

> † For certain open source projects we sponsor support for custom domains. Please contact us to find out if yours applies.

Your project has more stars than mine so you might have better luck 👍

**Comment by ngryman** [comment]
@styfle Unfortunately, I've contacted them several times, without success... The `https` feature was asked a lot so I've taken the Premium plan, for now... I'm hoping I'll be able to downgrade to OSS after that.

**Comment by ngryman** [comment]
And... it's alive!

![](https://cdn.zapier.com/storage/photos/ddcb7e66d9c2c431c54c4272fccea9a3.png)

**Comment by paulmolluzzo** [comment]
So awesome! Thanks!
