### ISSUE TITLE
support uglify

### ISSUE THREAD

**Issue by StephanHoyer** [ngryman/badge-size#68]
would be great to allow to get the filesize when uglified. I have no uglified version in my repo but want to show the size taking uglification into account.

Would be great, if you would support this.

**Comment by ngryman** [comment]
Hey,

I would like to keep Badge Size as simple as possible and be as agnostic as possible when it comes to the file content. Adding Uglify here would make Badge Size aware of JavaScript and start messing with its content. It's only made to advertise the size of a given file in your repo. The rest is left to the developer.

If you do want to advertise the uglified version of your file, you could have an uglified version of your file in your `npm` package and reference that URL (ie. `dist/mylib.min.js`).

**Comment by paulmelnikow** [comment]
Just a heads up that Shields recently added a badge for Bundlephobia, which shows a library's minified or minzipped size. It hasn't been deployed yet but hopefully will be soon. badges/shields#1481
