### ISSUE TITLE
Ambiguity of display

### ISSUE THREAD

**Issue by PhiLhoSoft** [ngryman/badge-size#7]
Your examples show 3.68 kB. Does this means it is around 3,680 bytes? The small k is ambiguous... Traditionally, we use KB for file sizes (except hard disk manufacturers, but they cheat).

Perhaps alternatively you can display as KiB, MiB and so on. This is increasingly popular and people are used to that already.

**Comment by ngryman** [comment]
Yup, the size is expressed in `kB` (kilobytes), not in `KiB` (kibibytes) or `KB`. So yes 3.68kB = 3.680 bytes.
I'm using [pretty-bytes](https://github.com/sindresorhus/pretty-bytes) under the hood, this has been discussed here if you want more details: https://github.com/sindresorhus/pretty-bytes/issues/17.
