### ISSUE TITLE
Public API?

### ISSUE THREAD

**Issue by styfle** [ngryman/badge-size#71]
Consider adding a `.json` file format that returns raw json data instead of an image.

This would allow badge rendering services such as https://badgen.net to be used with this service.

/cc @amio

**Comment by ngryman** [comment]
@styfle Oh that's a very interesting idea, I like it!

So I guess I could support the `.json` extension and return a JSON object like this:
```js
{
  compression: 'gzip' | 'brotli' | null,
  label: string,
  color: string,
  style: 'flat' | 'flat-square' | 'plastic',
  max: number?,
  softmax: number?
}
```

**Comment by styfle** [comment]
I think that should do it 👍 

I would image the `style` would be irrelevant for the purposes of Badgen since it will get overridden, but might as well leave it in there in case someone else wants to use it.

@amio Any other thoughts on this?

**Comment by ngryman** [comment]
> I would image the style would be irrelevant for the purposes of Badgen since it will get overridden, but might as well leave it in there in case someone else wants to use it.

Yup agree with that statement. I'm just reflecting query string parameters just in case the consumer wants them. I could also group all them like this:
```js
{
  size: string,
  color: string, // can be dynamically modified with max/softmax
  options: {
    compression: 'gzip' | 'brotli' | null,
    label: string,
    color: string,
    style: 'flat' | 'flat-square' | 'plastic',
    max: number?,
    softmax: number?
  }
}
```

**Comment by amio** [comment]
Return all size in a single endpoint would be more handy 🤗 e.g.:
```
https://api.badgesize.io/json/ngryman/badge-size/master/index.js
```
returns:
```
{
  size: string,
  gzippedSize: string,
  brotliSize: string,
  color: string
}
```

About the options, I think the query params could be omitted. If the querier pass the params in, they should not need to get those params from results, right? :D

**Comment by ngryman** [comment]
Hey @amio,

Thanks for your feedback!

I would not be in favor or returning all sizes at once as it would put load on the server and involve code changes specifically for this case. The vast majority of the time, people only advertise one kind of size. I would consider displaying several kind of sizes at once as an edge case that the user would have to deal with like: simply issue several requests ¯\_(ツ)_/¯

For the options, I was thinking of a scenario where the end user was not passing the query string parameters himself (ie. `badgesize` behind a proxy) but wanted to get the initial options back for some reason. But I guess that's redundant in most cases. So let's strip them for now!

Let's go with a simple:
```js
{
  size: string,
  color: string
}
```

**Comment by amio** [comment]
That would be good enough 💪

**Comment by amio** [comment]
Great, what's the endpoint for this api?

**Comment by amio** [comment]
Hi @ngryman, what about offering `color` as RGB? Would be more compatible with other client which doesn't have Shields's color schema.

**Comment by ngryman** [comment]
That's a very good idea! I'm gonna bring hex colors support and alias shields named colors to those colors, so other services can just rely on hex colors.

**Comment by ngryman** [comment]
👋 @amio, sorry for the late answer. It's now live at http://next.badgesize.io/. Would you mind giving it a try? If everything is ok, I'll deploy it to http://img.badgesize.io/.

**Comment by amio** [comment]
It works seamlessly 👍

USAGE

    https://badgen.net/https/badgesize-u29v2mhdzfej.runkit.sh/:compression/:filepath...

EXAMPLES

* https://badgen.net/https/badgesize-u29v2mhdzfej.runkit.sh/normal/amio/badgen/master/README.md
* https://badgen.net/https/badgesize-u29v2mhdzfej.runkit.sh/brotli/amio/badgen/master/README.md
* https://badgen.net/https/badgesize-u29v2mhdzfej.runkit.sh/gzip/amio/badgen/master/README.md

RUNKIT NOTEBOOK

https://runkit.com/amio/badgesize

**Comment by ngryman** [comment]
@amio Awesome, closing this. Thanks again for the suggestion!

**Comment by styfle** [comment]
@ngryman Is this deployed to production? img.badgesize.io

**Comment by ngryman** [comment]
It's live now! 🎉

**Comment by styfle** [comment]
@amio Should this be added to Badgen as a proper endpoint instead of relying on runkit?

**Comment by amio** [comment]
Yeap, the runkit endpoint are for handy testing :D

**Comment by amio** [comment]
It's live now https://badgen.net/#badgesize

**Comment by styfle** [comment]
Nice! But it looks like it only works for GitHub urls? However, I often use badge size for build output which doesn’t get checked into GitHub. 

For example, see https://GitHub.com/styfle/copee

**Comment by styfle** [comment]
Oops, not sure how I missed that last example! Thanks! 🎉
