### ISSUE TITLE
Can It use for total repo size?

### ISSUE THREAD

**Issue by iho4741** [ngryman/badge-size#72]
I see the **readme.md** tell only about file size. I wonder if it's can calculate a total of repository size.

**Comment by styfle** [comment]
No, badge-size cannot but Package Phobia can 😄 

https://github.com/styfle/packagephobia

**Comment by ngryman** [comment]
@iho4741 Nope sorry, `badge-size` is meant to be very simple. `packagephobia` may be a good alternative as @styfle suggested.
