### ISSUE TITLE
QUESTION: gzip size calculation

### ISSUE THREAD

**Issue by edwardfhsiao** [ngryman/badge-size#73]
Hi, I wonder how does it calculate the size when you point out only one ```index.js``` file?

For example, I have 4 files in ```repo/master/lib/```
```sh
a.js //300b
b.js //800b
c.js //400b

index.js // 1b
```

```js
//index.js
'use strict';
...
var _a = require('./a.js');
var _b = require('./b.js');
var _c = require('./c.js');
...
```

and the result of ```http://img.badgesize.io/dummy/repo/master/lib/index.js.svg?compression=gzip``` will most likely be **1b** instead of total **300 + 800 + 400 + 1**.

Am I understand it correctly?

**Comment by styfle** [comment]
Yes, badgesize only looks at the file you give it so it would be 1 byte.

However, there are other tools to solve your problem.

If you publish your repository to npm, you can use https://bundlephobia.com which will actually bundle the files with webpack and tell you the minified or min+gzip size.

For example, here's what the badges look like for react:

![min](https://badgen.net/bundlephobia/min/react)

![gzip](https://badgen.net/bundlephobia/minzip/react)

See https://badgen.net/#bundlephobia

**Comment by edwardfhsiao** [comment]
@styfle thanks a lot
