### ISSUE TITLE
Borken? undefined-undefined-undefined.undefined

### ISSUE THREAD

**Issue by diegohaz** [ngryman/badge-size#75]
It stopped working: https://img.badgesize.io/https://unpkg.com/constate?style=flat-square

![size](https://img.badgesize.io/https://unpkg.com/constate?style=flat-square)

**Comment by ngryman** [comment]
@diegohaz Thanks for reporting. PR incoming.

**Comment by ngryman** [comment]
Ok, it should work now, could you confirm it works for you too? If it's 👌I'll deploy it!
https://badge-size-osnkxuxvvn.now.sh/https://unpkg.com/constate?style=flat-square

**Comment by diegohaz** [comment]
It works for me. Thank you. :)
