### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by franciscop-sc** [ngryman/badge-size#84]
It seems that Zeit Now 1.0 has been removed and this no longer works. See example:
- Source: https://github.com/franciscop/statux/blob/master/index.min.js
- Badge (not working): https://img.badgesize.io/franciscop/statux/master/index.min.js.svg?compression=gzip
- [Zeit Now 1.0 removal notice](https://mailchi.mp/f923e55efe1d/simplified-pricing-1087517)

**Comment by ngryman** [comment]
It didn't migrated the `img.badgesize.io` subdomain. It should be fixed now!

**Comment by franciscop-sc** [comment]
Awesome! Thank you so much for the fix!
